version: '3'

services:
  tester:
    image: telegraf
    volumes:
      - "./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    depends_on:
      - influxdb
    restart: on-failure
  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
  web:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    restart: on-failure
    user: "104"
    volumes: 
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini:ro"
      - "./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/telegraf.yaml:ro"
      - "./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/network.yaml:ro"
      - "./grafana/dashboard.json:/etc/grafana/dashboards/network.json:ro"
    environment: 
      - GF_DATABASE_TYPE=sqlite3