version: '3'

services:
  tester:
    image: telegraf
    volumes:
      - "./telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    depends_on:
      - influxdb
    restart: on-failure
  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
  web:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    restart: on-failure
    user: "104"
    environment: 
      - GF_DATABASE_TYPE=sqlite3